name: Android CI with Gradle

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Print Java version
        run: java -version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up GitHub Maven credentials
        run: |
          echo "gpr.usr=${{ github.actor }}" >> $GITHUB_ENV
          echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run unit tests with Gradle
        run: |
          ./gradlew opensrp-chw-skeleton:clean \
                    opensrp-chw-skeleton:jacocoTestReport \
                    --stacktrace \
                    -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Javadoc with Gradle
        run: ./gradlew javadoc
        env:
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: opensrp-chw-skeleton/build/reports/jacoco/jacocoRootReport/merged.xml
          coverage-format: jacoco